#!/bin/bash
pkg update && pkg upgrade -y
apt install wget -y

wget https://github.com/NekoKatoriChan/Stable-Diffusion-on-Termux/raw/refs/heads/main/bin/sd -O $PREFIX/bin/sd
wget https://raw.githubusercontent.com/NekoKatoriChan/Stable-Diffusion-on-Termux/refs/heads/main/compoment/sd-ez -O $PREFIX/bin/sd-ez
wget https://raw.githubusercontent.com/NekoKatoriChan/Stable-Diffusion-on-Termux/refs/heads/main/compoment/config -O ~/.sd-config

chmod +x $PREFIX/bin/sd
chmod +x $PREFIX/bin/sd-ez
clear
echo 'Installation completed! To run Stable Diffusion, run "sd". For easy mode, run "sd-ez"'
